include: package:lints/recommended.yaml

analyzer:
  strong-mode:
    implicit-casts: true
    implicit-dynamic: true

linter:
  rules:
    curly_braces_in_flow_control_structures: false
    avoid_types_on_closure_parameters: true
    avoid_void_async: true
    await_only_futures: true
    camel_case_types: true
    cancel_subscriptions: true
    close_sinks: true
    constant_identifier_names: true
    control_flow_in_finally: true
    directives_ordering: true
    empty_statements: true
    hash_and_equals: true
    implementation_imports: true
    non_constant_identifier_names: true
    package_api_docs: true
    package_names: true
    package_prefixed_library_names: true
    test_types_in_equals: true
    throw_in_finally: true
    unnecessary_brace_in_string_interps: true
    unnecessary_getters_setters: true
    unnecessary_new: true
    unnecessary_statements: true
    prefer_const_constructors: true
