name: ble_data_converter
description: This package is for easy conversion to rawdata(List<int>) to be sent to BLE devices, etc.
version: 1.0.0
repository: https://github.com/den0206/ble_data_converter
platforms:
  android:
  ios:

environment:
  sdk: '>=2.18.2 <4.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  date_utils: ^0.2.0
  lints: ^4.0.0
  test: ^1.25.8
